//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnMonHoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanHoi
    {
        public string TenKH { get; set; }
        public string Email { get; set; }
        public string DienThoaiKH { get; set; }
        public string NoiDung { get; set; }
        public int MaPhanHoi { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
    }
}
